# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos-6.5-docker-0.7.6-x86_64"

  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision "shell", path: "config.d/base.sh"

  config.vm.provider :virtualbox do |v, override|
    v.customize ["modifyvm", :id, "--memory", "1024"]
  end
end
