all:

node01:
	mkdir -p shared.d/$@
	vagrant up $@

node02:
	mkdir -p shared.d/$@
	vagrant up $@

node03:
	mkdir -p shared.d/$@
	vagrant up $@

node04:
	mkdir -p shared.d/$@
	vagrant up $@

node05:
	mkdir -p shared.d/$@
	vagrant up $@
