# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos-6.5-docker-0.8.0-x86_64-with-sshd"

  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision "shell", path: "config.d/base.sh"

  config.vm.provider :virtualbox do |v, override|
    v.customize ["modifyvm", :id, "--memory", "1024"]
  end

  # -icc=true (default)
  config.vm.define "node01" do |node|
    node.vm.hostname = "node01"
    node.vm.provision "shell", path: "config.d/#{node.vm.hostname}.sh"
    node.vm.synced_folder "shared.d/#{node.vm.hostname}", "/vagrant"
  end

  # -icc=false
  config.vm.define "node02" do |node|
    node.vm.hostname = "node02"
    node.vm.provision "shell", path: "config.d/#{node.vm.hostname}.sh"
    node.vm.synced_folder "shared.d/#{node.vm.hostname}", "/vagrant"
  end

  # -icc=false, -link, single relation
  config.vm.define "node03" do |node|
    node.vm.hostname = "node03"
    node.vm.provision "shell", path: "config.d/#{node.vm.hostname}.sh"
    node.vm.synced_folder "shared.d/#{node.vm.hostname}", "/vagrant"
  end

  # -icc=false, -link, multi relation
  config.vm.define "node04" do |node|
    node.vm.hostname = "node04"
    node.vm.provision "shell", path: "config.d/#{node.vm.hostname}.sh"
    node.vm.synced_folder "shared.d/#{node.vm.hostname}", "/vagrant"
  end

  # -icc=false, duplicated -name <name>
  config.vm.define "node05" do |node|
    node.vm.hostname = "node05"
    node.vm.provision "shell", path: "config.d/#{node.vm.hostname}.sh"
    node.vm.synced_folder "shared.d/#{node.vm.hostname}", "/vagrant"
  end

  # -icc=false, custom ctimage
  config.vm.define "node06" do |node|
    node.vm.hostname = "node06"
    node.vm.provision "shell", path: "config.d/#{node.vm.hostname}.sh"
    node.vm.synced_folder "shared.d/#{node.vm.hostname}", "/vagrant"
  end
end
