# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos-6.5-docker-0.7.2-x86_64"

  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision "shell", path: "config.d/base.sh"

  # -icc=false (default)
  config.vm.define "node01" do |node|
    node.vm.provision "shell", path: "config.d/node01.sh"
  end

  # -icc=true
  config.vm.define "node02" do |node|
    node.vm.provision "shell", path: "config.d/node02.sh"
  end
end
